//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    /// <summary>
    /// Entity for account table
    /// </summary>
    public partial class Account
    {
        public int employeeId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string roleCode { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Employee Employee { get; set; }
    }
}