//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Database context for GB_Tasklogtracker_D1 database
    /// </summary>
    public partial class GB_Tasklogtracker_D1Context : DbContext
    {
        public GB_Tasklogtracker_D1Context() : base("name=GB_Tasklogtracker_D1Context")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<HighLevelEstimate> HighLevelEstimates { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<ReferenceType> ReferenceTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskAudit> TaskAudits { get; set; }
        public virtual DbSet<TaskAuditType> TaskAuditTypes { get; set; }
        public virtual DbSet<TaskReference> TaskReferences { get; set; }
        public virtual DbSet<TaskStatu> TaskStatus { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Urgency> Urgencies { get; set; }
        public virtual DbSet<Worksheet> Worksheets { get; set; }
        public virtual DbSet<WorksheetAudit> WorksheetAudits { get; set; }
        public virtual DbSet<WorksheetStatu> WorksheetStatus { get; set; }
    }
}