//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskAudits = new HashSet<TaskAudit>();
            this.TaskReferences = new HashSet<TaskReference>();
            this.Worksheets = new HashSet<Worksheet>();
        }
    
        public int taskId { get; set; }
        public int primaryContact { get; set; }
        public Nullable<int> secondaryContact { get; set; }
        public System.DateTime dateLogged { get; set; }
        public System.DateTime dateSubmmited { get; set; }
        public int serviceTeam { get; set; }
        public int serviceGroup { get; set; }
        public string platform { get; set; }
        public string urgency { get; set; }
        public int businessUnit { get; set; }
        public string environment { get; set; }
        public string category { get; set; }
        public int application { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string highLevelEstimate { get; set; }
        public string links { get; set; }
        public string taskStatus { get; set; }
    
        public virtual Application Application1 { get; set; }
        public virtual BusinessUnit BusinessUnit1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Environment Environment1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual HighLevelEstimate HighLevelEstimate1 { get; set; }
        public virtual Platform Platform1 { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual Urgency Urgency1 { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAudit> TaskAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskReference> TaskReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worksheet> Worksheets { get; set; }
    }
}
