//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskId { get; set; }
        public int primaryContact { get; set; }
        public int secondaryContact { get; set; }
        public System.DateTime dateLogged { get; set; }
        public System.DateTime dateSubmmited { get; set; }
        public int serviceTeam { get; set; }
        public int serviceGroup { get; set; }
        public string platform { get; set; }
        public string urgency { get; set; }
        public int businessUnit { get; set; }
        public string environment { get; set; }
        public string category { get; set; }
        public int application { get; set; }
        public string reference { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string highLevelEstimate { get; set; }
        public string links { get; set; }
        public string taskStatusCode { get; set; }
    
        public virtual Application Application1 { get; set; }
        public virtual BusinessUnit BusinessUnit1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Environment Environment1 { get; set; }
        public virtual HighLevelEstimate HighLevelEstimate1 { get; set; }
        public virtual Platform Platform1 { get; set; }
        public virtual Reference Reference1 { get; set; }
        public virtual ServiceGroup ServiceGroup1 { get; set; }
        public virtual Urgency Urgency1 { get; set; }
        public virtual Team Team { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
    }
}
