//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    /// <summary>
    /// Entity for task reference table
    /// </summary>
    public partial class TaskReference
    {
        public int taskReferenceId { get; set; }
        public int task { get; set; }
        public int reference { get; set; }
    
        public virtual Reference Reference1 { get; set; }
        public virtual Task Task1 { get; set; }
    }
}