//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worksheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worksheet()
        {
            this.WorksheetAudits = new HashSet<WorksheetAudit>();
        }
    
        public int worksheetId { get; set; }
        public int employee { get; set; }
        public int task { get; set; }
        public string worksheetStatus { get; set; }
        public System.DateTime dateAssigned { get; set; }
        public string notes { get; set; }
        public decimal timeSpent { get; set; }
        public Nullable<bool> overtime { get; set; }
        public Nullable<bool> onCall { get; set; }
        public string links { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual WorksheetStatu WorksheetStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksheetAudit> WorksheetAudits { get; set; }
    }
}
