//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLog2ndGen.Models
{
    /// <summary>
    /// Entity for worksheet audit table
    /// </summary>
    public partial class WorksheetAudit
    {
        public int worksheetAuditId { get; set; }
        public int worksheet { get; set; }
        public System.DateTime dateLogged { get; set; }
        public int loggedBy { get; set; }
        public string notes { get; set; }
        public decimal timeSpent { get; set; }
        public string worksheetStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Worksheet Worksheet1 { get; set; }
        public virtual WorksheetStatu WorksheetStatu { get; set; }
    }
}